time:
  start: "2012-03-01T00:00:00"
  end: "2012-04-01T00:00:00"
space:
collumns: null
  bbox: null
  polygon_str: '130 -10,240 -10,240 10,130 10,130 -10'
  polygon_file: null
  polygon_crs: "EPSG:4326"
problematic_months:
  cadence_seconds: null
  missing_threshold_pct: null
  report_path: null
export:
  format: csv
  path: "./query_output.csv"
  strict_cf: False
backend:
  url: null
  table: null
  srid: 4326